spring:
  application:
        name: playstation-scraper
  config:
      import: "optional:configserver:http://config-server:8088"
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 5000
        max-interval: 5000
        multiplier: 1.0

  data:
    redis:
      host: localhost
      port: 6379