steps:
  # -1. Recuperar el usuario de Docker y guardarlo en un archivo
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "obtener-docker-username"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud secrets versions access latest --secret=_DOCKER_USERNAME > docker-username.txt

  # -0. Recuperar la contraseña de Docker y guardarla en un archivo
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "obtener-docker-password"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud secrets versions access latest --secret=_DOCKER_PASSWORD > docker-password.txt

  # 0. Probar login y versión de Docker Compose
  - name: "docker:28.2.2-cli"
    id: "test-docker-compose-version"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cat docker-password.txt | docker login -u "$(cat docker-username.txt)" --password-stdin
        docker compose version

  # 1. Dar permisos de ejecución y compilar todos los servicios Java usando el script personalizado
  - name: "maven:3.9.9-eclipse-temurin-24"
    id: "chmod-and-compilar-java"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        chmod +x ./mvn.sh
        chmod +x ./mvnw || true
        find . -name mvnw -exec chmod +x {} \;
        ./mvn.sh

  # 2. Recuperar el secreto _ENV y crear el archivo .env para el frontend
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "crear-env-frontend"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud secrets versions access latest --secret=_ENV > .env

  # 3. Recuperar el secreto _UNIFICADOR_ENV y crear el archivo unificador-db-secrets.env
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "crear-env-unificador"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud secrets versions access latest --secret=_UNIFICADOR_ENV > unificador-db-secrets.env

  # 6. Renombrar .env.example a .env antes del build de Docker Compose
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "renombrar-env"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        mv frontend/.env.example frontend/.env

  # 7. Construir las imágenes Docker de todos los servicios definidos en docker-compose
  - name: "docker:28.2.2-cli"
    id: "build-docker"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        docker compose build

  # 8-9. Login en Docker Hub y pushear las imágenes al registro en un solo paso
  - name: "docker:28.2.2-cli"
    id: "docker-login-and-push"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cat docker-password.txt | docker login -u "$(cat docker-username.txt)" --password-stdin
        docker compose push

  # 10. Desplegar en la VM de Google Cloud por SSH
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-vm"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud compute ssh crosscompare --zone us-central1-c --project onyx-messenger-461611-t7 --command '
          cd /home/rachidchaibali03 && \
          docker compose down && \
          docker image prune -af && \
          docker compose up -d --build
        '

options:
  logging: CLOUD_LOGGING_ONLY
