steps:
  # 0. Dar permisos de ejecuci칩n al script mvn.sh
  - name: "maven:3.9.6-eclipse-temurin-21"
    id: "chmod-mvn"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        chmod +x ./mvn.sh

  # 1. Compilar todos los servicios Java usando el script personalizado
  - name: "maven:3.9.6-eclipse-temurin-21"
    id: "compilar-java"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        ./mvn.sh

  # 2. Recuperar el secreto ENV y crear el archivo .env para el frontend
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "crear-env-frontend"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud secrets versions access latest --secret=ENV > .env

  # 3. Recuperar el secreto UNIFICADOR_ENV y crear el archivo unificador-db-secrets.env
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "crear-env-unificador"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud secrets versions access latest --secret=UNIFICADOR_ENV > unificador-db-secrets.env

  # 4. Renombrar .env.example a .env antes del build de Docker Compose
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "renombrar-env"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        mv frontend/.env.example frontend/.env

  # 5. Construir las im치genes Docker de todos los servicios definidos en docker-compose
  - name: "docker/compose:1.29.2"
    id: "build-docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker compose build

  # 6. Login en Docker Hub usando los secretos de usuario y contrase침a
  - name: "docker/compose:1.29.2"
    id: "docker-login"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "$$DOCKERFILE_PASSWORD" | docker login -u "$$DOCKERFILE_USERNAME" --password-stdin
    secretEnv: ['DOCKERFILE_USERNAME', 'DOCKERFILE_PASSWORD']

  # 7. Pushear las im치genes al registro
  - name: "docker/compose:1.29.2"
    id: "push-docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker compose push

  # 8. Desplegar en la VM de Google Cloud por SSH
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-vm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh crosscompare --zone us-central1-c --project onyx-messenger-461611-t7 --command '
          cd /home/rachidchaibali03 && \
          docker compose down && \
          docker image prune -af && \
          docker compose up -d --build
        '

availableSecrets:
  secretManager:
    - versionName: projects/onyx-messenger-461611-t7/secrets/_DOCKERFILE_USERNAME/versions/latest
      env: 'DOCKERFILE_USERNAME'
    - versionName: projects/onyx-messenger-461611-t7/secrets/_DOCKERFILE_PASSWORD/versions/latest
      env: 'DOCKERFILE_PASSWORD'

options:
  logging: CLOUD_LOGGING_ONLY
