version: '3.8'

services:
  api-gateway:
    build:
      context: ./API-Gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  playstation-scraper:
    build:
      context: ./PlaystationScraper
      dockerfile: Dockerfile
    ports:
      - "8080:8081"

  xbox-scraper:
    build:
      context: ./XboxScraper
      dockerfile: Dockerfile
    ports:
      - "8080:8082"

  user-manager:
    build:
      context: ./UserManager
      dockerfile: Dockerfile
    ports:
      - "8080:8083"
