version: '3.8'

services:
  api-gateway:
    build:
      context: ./API-Gateway
      dockerfile: Dockerfile
    image: rachidchaibugr/api-gateway
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: rachidchaibugr/frontend
    ports:
      - "3000:80"

  playstation-scraper:
    build:
      context: ./PlaystationScraper
      dockerfile: Dockerfile
    image: rachidchaibugr/playstation-scraper
    ports:
      - "8081:8080"

  xbox-scraper:
    build:
      context: ./XboxScraper
      dockerfile: Dockerfile
    image: rachidchaibugr/xbox-scraper
    ports:
      - "8082:8080"

  steam-api:
    build:
      context: ./SteamAPI
      dockerfile: Dockerfile
    image: rachidchaibugr/steam-api
    ports:
      - "8083:8080"

  user-manager:
    build:
      context: ./UserManager
      dockerfile: Dockerfile
    image: rachidchaibugr/user-manager
    ports:
      - "8084:8080"

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  config-server:
    build:
      context: ./ConfigServer
      dockerfile: Dockerfile
    image: rachidchaibugr/config-server
    ports:
      - "8888:8888"

  eureka:
    build:
      context: ./Eureka
      dockerfile: Dockerfile
    image: rachidchaibugr/eureka
    ports:
      - "8761:8761"

  unificador:
    build:
      context: ./Unificador
      dockerfile: Dockerfile
    image: rachidchaibugr/unificador
    ports:
      - "8085:8080"

volumes:
  redis_data: