server:
    port: 8080

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/eureka/
        fetch-registry: true
        register-with-eureka: true
        registry-fetch-interval-seconds: 5
        initial-instance-info-replication-interval-seconds: 5

spring:
  cloud:
    gateway:
        routes:
          - id: playstation-scraper
            uri: lb://PLAYSTATION-SCRAPER
            predicates:
              - Path=/playstation-scraper/**
            filters:
              - StripPrefix=1
          - id: xbox-scraper
            uri: lb://XBOX-SCRAPER
            predicates:
              - Path=/xbox-scraper/**
            filters:
              - StripPrefix=1
          - id: steam-api
            uri: lb://STEAM-API
            predicates:
              - Path=/steam-api/**
            filters:
              - StripPrefix=1
          - id: user-manager
            uri: lb://USER-MANAGER
            predicates:
              - Path=/user-manager/**
            filters:
              - StripPrefix=1
          - id: unificador
            uri: lb://UNIFICADOR
            predicates:
              - Path=/unificador/**
            filters:
              - StripPrefix=1

