server:
    port: 8080

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/eureka/
        fetch-registry: true
        register-with-eureka: true
        registry-fetch-interval-seconds: 5
        initial-instance-info-replication-interval-seconds: 5

spring:
  cloud:
    gateway:
        routes:
          - id: playstation-scraper
            uri: lb://playstation-scraper
            predicates:
              - Path=/playstation-scraper/**
              
          - id: xbox-scraper
            uri: lb://xbox-scraper
            predicates:
              - Path=/xbox-scraper/**

          - id: steam-api
            uri: lb://steam-api
            predicates:
              - Path=/steam-api/**

          - id: user-manager
            uri: lb://user-manager
            predicates:
              - Path=/user-manager/**

          - id: unificador
            uri: lb://unificador
            predicates:
              - Path=/unificador/**

