server:
    port: 8080

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/eureka/
        fetch-registry: true
        register-with-eureka: true
        registry-fetch-interval-seconds: 5
        initial-instance-info-replication-interval-seconds: 5

spring:
    datasource:
        url: jdbc:mariadb://unificador-db:3306/db-unificador
        username: unificador_user
        password: unificador_pass
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MariaDBDialect
    cloud:
        discovery:
            enabled: true
    data:
        redis:
            host: redis
            port: 6379

